import csv
from collections import Counter
from pathlib import Path
from html import escape


RESULTS_FILE = Path("test_results.csv")
SVG_FILE = Path("test_summary.svg")
REPORT_FILE = Path("VALIDATION_REPORT.md")


def load_results():
    if not RESULTS_FILE.exists():
        raise FileNotFoundError(
            "test_results.csv was not found. Run: python3 test_runner.py"
        )

    with RESULTS_FILE.open("r", newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file)
        rows = list(reader)

    if not rows:
        raise ValueError("test_results.csv contains no test results.")

    return rows


def find_status(row):
    for key, value in row.items():
        if key and key.strip().lower() in {"status", "result", "outcome"}:
            return str(value).strip().upper()
    return "UNKNOWN"


def create_svg(counts):
    passed = counts.get("PASS", 0) + counts.get("PASSED", 0)
    failed = counts.get("FAIL", 0) + counts.get("FAILED", 0)
    errors = counts.get("ERROR", 0)
    total = passed + failed + errors

    if total == 0:
        total = sum(counts.values())

    pass_rate = (passed / total * 100) if total else 0

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="900" height="430"
viewBox="0 0 900 430">
  <rect width="900" height="430" rx="24" fill="#0d1117"/>
  <text x="50" y="65" fill="#f0f6fc" font-family="Arial, sans-serif"
        font-size="30" font-weight="bold">
    Virtual Embedded Device Validation
  </text>
  <text x="50" y="100" fill="#8b949e" font-family="Arial, sans-serif"
        font-size="17">
    Automated test execution summary
  </text>

  <rect x="50" y="135" width="240" height="150" rx="16" fill="#161b22"
        stroke="#238636" stroke-width="3"/>
  <text x="170" y="185" text-anchor="middle" fill="#8b949e"
        font-family="Arial, sans-serif" font-size="19">PASSED</text>
  <text x="170" y="255" text-anchor="middle" fill="#3fb950"
        font-family="Arial, sans-serif" font-size="58" font-weight="bold">
    {passed}
  </text>

  <rect x="330" y="135" width="240" height="150" rx="16" fill="#161b22"
        stroke="#da3633" stroke-width="3"/>
  <text x="450" y="185" text-anchor="middle" fill="#8b949e"
        font-family="Arial, sans-serif" font-size="19">FAILED</text>
  <text x="450" y="255" text-anchor="middle" fill="#f85149"
        font-family="Arial, sans-serif" font-size="58" font-weight="bold">
    {failed}
  </text>

  <rect x="610" y="135" width="240" height="150" rx="16" fill="#161b22"
        stroke="#d29922" stroke-width="3"/>
  <text x="730" y="185" text-anchor="middle" fill="#8b949e"
        font-family="Arial, sans-serif" font-size="19">ERRORS</text>
  <text x="730" y="255" text-anchor="middle" fill="#e3b341"
        font-family="Arial, sans-serif" font-size="58" font-weight="bold">
    {errors}
  </text>

  <text x="50" y="340" fill="#f0f6fc" font-family="Arial, sans-serif"
        font-size="20">Pass rate</text>
  <rect x="170" y="320" width="680" height="28" rx="14" fill="#30363d"/>
  <rect x="170" y="320" width="{680 * pass_rate / 100:.1f}" height="28"
        rx="14" fill="#238636"/>
  <text x="850" y="390" text-anchor="end" fill="#3fb950"
        font-family="Arial, sans-serif" font-size="24" font-weight="bold">
    {pass_rate:.1f}%
  </text>
</svg>
"""

    SVG_FILE.write_text(svg, encoding="utf-8")
    return passed, failed, errors, total, pass_rate


def markdown_value(value):
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def create_markdown_report(rows, passed, failed, errors, total, pass_rate):
    headers = list(rows[0].keys())

    table_header = "| " + " | ".join(markdown_value(h) for h in headers) + " |"
    table_separator = "| " + " | ".join("---" for _ in headers) + " |"

    table_rows = []
    for row in rows:
        table_rows.append(
            "| "
            + " | ".join(markdown_value(row.get(header, "")) for header in headers)
            + " |"
        )

    report = f"""# Validation Report

![Automated test summary](test_summary.svg)

## Summary

- **Total tests:** {total}
- **Passed:** {passed}
- **Failed:** {failed}
- **Errors:** {errors}
- **Pass rate:** {pass_rate:.1f}%

## Test Results

{table_header}
{table_separator}
{chr(10).join(table_rows)}

## Scope

This report was generated by a Python-based validation framework for a
simulated embedded device. The suite verifies communication, device
information, GPIO behavior, sensor ranges, heartbeat operation, invalid-input
handling, and controlled fault detection.

## Important Note

This is a software simulation project. It demonstrates automated validation
methods without claiming testing on physical hardware.
"""

    REPORT_FILE.write_text(report, encoding="utf-8")


def main():
    rows = load_results()
    counts = Counter(find_status(row) for row in rows)

    passed, failed, errors, total, pass_rate = create_svg(counts)
    create_markdown_report(
        rows, passed, failed, errors, total, pass_rate
    )

    print("VALIDATION REPORT GENERATED")
    print("=" * 40)
    print(f"Passed:    {passed}")
    print(f"Failed:    {failed}")
    print(f"Errors:    {errors}")
    print(f"Total:     {total}")
    print(f"Pass rate: {pass_rate:.1f}%")
    print(f"Created:   {SVG_FILE}")
    print(f"Created:   {REPORT_FILE}")


if __name__ == "__main__":
    main()
